// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yoty.Data;

namespace yoty.Migrations
{
    [DbContext(typeof(YotyContext))]
    [Migration("20201114183051_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Yoty.Data.Entities.BuyerAccountDetailsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("BuyerAccountDetailsEntity");
                });

            modelBuilder.Entity("Yoty.Data.Entities.BuyerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BuyerAccountDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("FacebookAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerAccountDetailsId");

                    b.HasIndex("FacebookAccountId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Yoty.Data.Entities.FacebookAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("FacebookAccountEntity");
                });

            modelBuilder.Entity("Yoty.Data.Entities.ParticipancyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BidId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidId1")
                        .HasColumnType("int");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumOfUnits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BidId1");

                    b.HasIndex("BuyerId");

                    b.ToTable("ParticipancyEntity");
                });

            modelBuilder.Entity("Yoty.Data.Entities.ProductBidEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BuyerEntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotenialSuplliersCounter")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitsCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerEntityId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Yoty.Data.Entities.SellerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewsCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Yoty.Data.Entities.SellerOfferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BidId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidId1")
                        .HasColumnType("int");

                    b.Property<int>("MinimumUnits")
                        .HasColumnType("int");

                    b.Property<string>("OfferDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OfferedPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublishedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BidId1");

                    b.HasIndex("SellerId1");

                    b.ToTable("SellerOfferEntity");
                });

            modelBuilder.Entity("Yoty.Data.Entities.BuyerEntity", b =>
                {
                    b.HasOne("Yoty.Data.Entities.BuyerAccountDetailsEntity", "BuyerAccountDetails")
                        .WithMany()
                        .HasForeignKey("BuyerAccountDetailsId");

                    b.HasOne("Yoty.Data.Entities.FacebookAccountEntity", "FacebookAccount")
                        .WithMany()
                        .HasForeignKey("FacebookAccountId");

                    b.Navigation("BuyerAccountDetails");

                    b.Navigation("FacebookAccount");
                });

            modelBuilder.Entity("Yoty.Data.Entities.ParticipancyEntity", b =>
                {
                    b.HasOne("Yoty.Data.Entities.ProductBidEntity", "Bid")
                        .WithMany("CurrentParticipancies")
                        .HasForeignKey("BidId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yoty.Data.Entities.BuyerEntity", "Buyer")
                        .WithMany("CurrentParticipancies")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Yoty.Data.Entities.ProductBidEntity", b =>
                {
                    b.HasOne("Yoty.Data.Entities.BuyerEntity", null)
                        .WithMany("CurrentBidsAndItemsCount")
                        .HasForeignKey("BuyerEntityId");
                });

            modelBuilder.Entity("Yoty.Data.Entities.SellerOfferEntity", b =>
                {
                    b.HasOne("Yoty.Data.Entities.ProductBidEntity", "Bid")
                        .WithMany("CurrentOffers")
                        .HasForeignKey("BidId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yoty.Data.Entities.SellerEntity", "Seller")
                        .WithMany("CurrentOffers")
                        .HasForeignKey("SellerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Yoty.Data.Entities.BuyerEntity", b =>
                {
                    b.Navigation("CurrentBidsAndItemsCount");

                    b.Navigation("CurrentParticipancies");
                });

            modelBuilder.Entity("Yoty.Data.Entities.ProductBidEntity", b =>
                {
                    b.Navigation("CurrentOffers");

                    b.Navigation("CurrentParticipancies");
                });

            modelBuilder.Entity("Yoty.Data.Entities.SellerEntity", b =>
                {
                    b.Navigation("CurrentOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
